# Generated by Django 3.0.3 on 2020-03-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_registered',
            field=models.DateField(),
        ),
    ]
