# Generated by Django 3.0.3 on 2020-02-16 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_guardianprofile_staffprofile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianprofile',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to='accounts.StudentProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(default='teacher', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(default='id', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='form',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='house',
            field=models.CharField(default='house', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='kcpe_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reg_no',
            field=models.CharField(default=3594, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='stream',
            field=models.CharField(default='south', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
