# Generated by Django 3.0.3 on 2020-02-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200216_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guardian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
