# Generated by Django 3.0.3 on 2020-02-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200216_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='house',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='kcpe_marks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='reg_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
