# Generated by Django 3.0.3 on 2020-02-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200216_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='kcpe_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
