# Generated by Django 3.0.3 on 2020-02-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_done', models.DateTimeField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_module.ExamType')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.StudentProfile', to_field='reg_no')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_module.Subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_module.Term')),
            ],
        ),
    ]
