# Generated by Django 3.0.3 on 2020-03-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
                ('greatest_lower_bound', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
