# Generated by Django 3.0.3 on 2020-02-18 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200217_2312'),
        ('exam_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date_done',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 15, 13, 50, 208513, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exam_module.ExamType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.StudentProfile', to_field='reg_no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam_module.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam_module.Term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examtype',
            name='name',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='name',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
