# Generated by Django 3.0.3 on 2020-03-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('exam_module', '0003_auto_20200301_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsDoneByStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.StudentProfile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_module.Subject')),
            ],
        ),
    ]
