# Generated by Django 3.0.3 on 2020-03-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_module', '0004_subjectsdonebystudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date_done',
            field=models.DateField(),
        ),
    ]
